---
- name: set content category
  cisco.meraki.meraki_mx_content_filtering:
    auth_key: '{{ auth_key }}'
    org_name: '{{ org_name }}'
    net_name: '{{ item.name }}'
    state: present
    blocked_categories: "{{ blockcat }}"
  loop: "{{ network.data }}"
  when: "'appliance' in item.product_types"
  loop_control:
    label: "{{ item.name }}"
