- name: meraki deployment
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
  vars_files:
    - vars/default.yml
  
  tasks:  
  - name: get Network ID
    cisco.meraki.meraki_network:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      state: query
    register: network

  - name: set content category
    cisco.meraki.meraki_mx_content_filtering:
      auth_key: '{{ auth_key }}'
      org_name: '{{ org_name }}'
      net_name: '{{ item.name }}'
      state: present
      blocked_categories: "{{ blockcat }}"
      blocked_urls: "{{ blockurl }}"
      allowed_urls: "{{ allowurl }}"
    loop: "{{ network.data }}"
    when: "'appliance' in item.product_types"
    loop_control:
      label: "{{ item.name }}"
