- name: meraki deployment
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
  vars_files:
    - vars/default.yml
  
  tasks:  
  - name: get Network ID
    cisco.meraki.meraki_network:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      state: query
    register: network

  - name: url lists
    import_tasks: mx_url_lists.yml
    when: url_lists_enabled

  - name: set content category
    import_tasks: mx_content_category.yml
    when: content_categories_enabled
