---

name: ansible
on:
  push:
    paths:
      - '!.github'

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        timeout-minutes: 1
      - name: run ansible container
        timeout-minutes: 3
        uses: docker://cytopia/ansible:latest
        with:
          args: ansible-playbook playbooks/playbook.yml --connection=local --extra-vars "auth_key=${{ secrets.MERAKIAPI }} org_name=${{ secrets.ORG }}"

