---

name: Release
'on':
  - push

defaults:
  run:
    working-directory: 'ansible-dir'

jobs:

  ansible:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible:latest
      volumes:
        - playbooks:/data
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible'
      - name: start playbook
        run: ansible-playbook playbook.yml --extra-vars --extra-vars "auth_key=${{ secrets.MERAKIAPI }} org_name=${{ secrets.ORG }}"
