---

name: ansible
'on':
  - push

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: run ansible container
        uses: docker://cytopia/ansible:latest
        with:
          args: ansible-playbook playbooks/playbook.yml --extra-vars "auth_key=${{ secrets.MERAKIAPI }} org_name=${{ secrets.ORG }}" -vvv

