name: CICD  # feel free to pick your own name

on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/vars/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
     
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
           playbooks/meraki.yml
        override-deps: |
          ansible
          ansible-lint
        
    - shell: bash
      env:
        auth_key: ${{ secrets.MERAKIAPI }}
        org_name: ${{ secrets.ORG }}
      run: sh ./scripts/entrypoint.sh
