---

name: Release
'on':
  - push

defaults:
  run:
    working-directory: 'ansible-dir'

jobs:

  ansible:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible:latest
      volumes:
        - playbooks:/data
    steps:
      - name: start playbook
        run: ansible-playbook playbooks/playbook.yml --extra-vars --extra-vars "auth_key=${{ secrets.MERAKIAPI }} org_name=${{ secrets.ORG }}"
